require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'OnulFrontEnd' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # 애플리케이션 루트 절대 경로
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # 최신 Masked View 모듈 사용
  pod 'RNCMaskedView', :path => '../node_modules/@react-native-masked-view/masked-view'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'


  target 'OnulFrontEndTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
